name: "DLNA"
guid: "33EBA9CD-7DA1-4720-967F-DD7DAE7B74A1"
imageUrl: ""
version: 3
targetAbi: "10.9.10.0"
framework: "net8.0"
owner: "jellyfin"
overview: "DLNA Service"
description: >
  Adds DLNA capability to Jellyfin

category: "General"
artifacts:
  - "Jellyfin.Plugin.Dlna.dll"
  - "Jellyfin.Plugin.Dlna.Model.dll"
  - "Jellyfin.Plugin.Dlna.Playback.dll"
  - "Rssdp.dll"
changelog: |-
  - restore video transcoding (#68) @flashka07
  - Update dependency Microsoft.AspNetCore.Authorization to v8.0.8 (#54) @renovate
  - Set publisher uri to http (#62) @disgustipated
  - Remove . from friendlyname for identifying LG TVs (#60) @disgustipated
